In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
df = pd.read_csv("NEW DATA.csv")

In [12]:
df

    Volume Ratio  pH  Temp  RPM Size
0              1   3    20  100  Max
1              5   3    35  100  Max
2              1   7    20  100  Max
3              5   7    30  100  Max
4             10   7    30  100  Max
5             10   8    30  100  Max
6             10   9    30  100  Min
7             20   7    30  100  Max
8             20   8    30  100  Max
9             20   9    30  100  Max
10            25   7    30  100  Max
11            10   8    50  300  Min
12            10   9    50  300  Min
13            20   8    50  300  Min
14            20   9    50  300  Min
15            10   8    60  300  Min
16            10   9    60  300  Min
17            20   8    60  300  Min
18            20   9    60  300  Min
19            10   8    60  500  Min
20            10   9    60  500  Min
21            20   8    60  500  Min
22            20   9    60  500  Min
23            10   8    60  600  Min
24            10   9    60  600  Min
25            20   8    60  600  MIn
26            20   9    60  600  Min

In [14]:
x = df[['Volume Ratio','pH','Temp','RPM']]
y = df['Size']

In [15]:
x

    Volume Ratio  pH  Temp  RPM
0              1   3    20  100
1              5   3    35  100
2              1   7    20  100
3              5   7    30  100
4             10   7    30  100
5             10   8    30  100
6             10   9    30  100
7             20   7    30  100
8             20   8    30  100
9             20   9    30  100
10            25   7    30  100
11            10   8    50  300
12            10   9    50  300
13            20   8    50  300
14            20   9    50  300
15            10   8    60  300
16            10   9    60  300
17            20   8    60  300
18            20   9    60  300
19            10   8    60  500
20            10   9    60  500
21            20   8    60  500
22            20   9    60  500
23            10   8    60  600
24            10   9    60  600
25            20   8    60  600
26            20   9    60  600

In [16]:
y

0     Max
1     Max
2     Max
3     Max
4     Max
5     Max
6     Min
7     Max
8     Max
9     Max
10    Max
11    Min
12    Min
13    Min
14    Min
15    Min
16    Min
17    Min
18    Min
19    Min
20    Min
21    Min
22    Min
23    Min
24    Min
25    MIn
26    Min
Name: Size, dtype: object

In [18]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.3,random_state = 0)

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
logmod = LogisticRegression()

In [22]:
logmod.fit(x_train,y_train)

C:\Users\hailj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()